### ISSUE TITLE
Update and Align Data Model with BPDM

### ISSUE THREAD

**Issue by fabiodmota** [eclipse-tractusx/vas-country-risk-backend#106]
## Issue Description
- **Requirement:** Adapat to BPDM data model. We need to change our backend implementation that communicates with the Gate. Checking the latest changes on BPDM 
- **Requirement:** This must be tested both in Dev and Int

## Product Information
- **Product Name:** vas-country-risk-backend
- **Repository Link:** [vas-country-risk-backend](https://github.com/eclipse-tractusx/vas-country-risk-backend)

## Tasks
- [ ] Update with the new Data Mode
- [ ] Validate on Dev 
- [ ] Validate on Int with EDC
