### ISSUE TITLE
Update Vulnerable Dependencies and Validate Code Quality

### ISSUE THREAD

**Issue by fabiodmota** [eclipse-tractusx/vas-country-risk-backend#20]
## Description
Detected vulnerabilities on  `vas-country-risk-backend` project that have vulnerabilities as reported by Veracode Trivy and Invicty. These dependencies need to be updated to ensure our application's security and stability. We also require the code to be validated on Sonar.

## Product Name
[vas-country-risk-backend](https://github.com/eclipse-tractusx/vas-country-risk-backend)

## Reproduction Steps
1. Run Veracode Trivy and Invicty on the latest codebase to see the listed vulnerabilities.
2. Verify the detected vulnerabilities.

## Expected Behavior
No vulnerabilities should be reported by Veracode Trivy or Invicty. Sonar should report good quality of code.

## Tasks
- [x] Identify and update the dependencies that have vulnerabilities as reported by Veracode Trivy and Invicty.
- [x] Ensure that the application functions correctly after updating these dependencies.
- [x] Validate the code on Sonar to ensure that there are no new issues and the quality of code is good.

## Hints
Remember to thoroughly test the application after updating the dependencies to ensure no new issues have been introduced.
