### ISSUE TITLE
Update ARC-42

### ISSUE THREAD

**Issue by fabiodmota** [eclipse-tractusx/vas-country-risk-backend#30]
## Issue Description
- **Problem:** The documentation on `ARC-42.md` currently has outdated information regarding the sharing controller. It needs to be updated to reflect the changes made from 'dashboard' to 'sharing'.

## Product Information
- **Related Document:** `ARC-42.md`
- **Related Document:** `User-Guide.md`
- **Repository Link:** [vas-country-risk-backend](https://github.com/eclipse-tractusx/vas-country-risk-backend)

## Tasks
- [x] Update the documentation in `ARC-42.md` to accurately represent the changes made to the sharing controller, specifically the change from 'dashboard' to 'sharing'.
- [x] Review and verify that the updated documentation is clear and accurate.
- [x] Validate both projects as the same ARC-42.md and UserGuide.md ( swagger only for backend )

### Todos
- [x] Update login page on https://github.com/eclipse-tractusx/vas-country-risk-backend/blob/main/docs/User-Guide.md#portal-to-dashboard section not updated to current one
- [x] Update image of table ( outdated since roles were inserted ) section https://github.com/eclipse-tractusx/vas-country-risk-backend/blob/main/docs/User-Guide.md#business-partner-table
- [x] Add image with roles view as an example https://github.com/eclipse-tractusx/vas-country-risk-backend/blob/main/docs/User-Guide.md#business-partner-table
- [x] Add image with roles view as an example for Customer and Supplier on section https://github.com/eclipse-tractusx/vas-country-risk/blob/main/docs/Arc42-Documentation.md#roles-rights-management
- [x] Update System Scope and Context with new Image proposed on standard document section https://github.com/eclipse-tractusx/vas-country-risk/blob/main/docs/Arc42-Documentation.md#system-scope-and-context
- [x] New endpoints needed to be added ( getUserFromCompany, updateReports and ShareReports) section https://github.com/eclipse-tractusx/vas-country-risk/blob/main/docs/Arc42-Documentation.md#endpoint-explanation
- [x] Move Sharing endpoints ( getAllRatingsScoresForEachBpn , getAllRatingsForCompany ) to Sharing controller part and update response objects
- [x] Response objects need to be updated on endpoints (GetUserRanges, getTableInfo, getCompanyBpns) section https://github.com/eclipse-tractusx/vas-country-risk/blob/main/docs/Arc42-Documentation.md#endpoint-explanation
 
## Hints for Resolution
- Ensure that the updated documentation is clear and reflects the current state of the system.
- Use precise and concise language to describe the changes to the sharing controller.

**Comment by alexsilva-CGI** [comment]
Documentation on both backend and frontend seems to be updated and good to be merged.
