### ISSUE TITLE
Deploy and Configuration on INT 

### ISSUE THREAD

**Issue by fabiodmota** [eclipse-tractusx/vas-country-risk-backend#69]
## Issue Description
We need to configure and deploy all new information for our apps int the INT env.

- **Requirement:**
- Deploy and configuration of Frontend
- Deploy and configuration of Backend
- Deploy and configuration of EDC Provider
- Deploy and configuration of EDC Consumer

## Product Information
- **Product Name:** vas-country-risk-backend
- **Repository Link:** [vas-country-risk-backend](https://github.com/eclipse-tractusx/vas-country-risk-backend)
- **FronEnd Repository Link:** [vas-country-risk](https://github.com/eclipse-tractusx/vas-country-risk)

## Tasks
- [ ] Update User for app on vault so we can login from the frontend with Portal
- [ ] Create and Update new technical User for Country Risk connection to Gate and Pool
- [ ] Add Roles to be configured with Country Risk Dashboard 
- [ ] Configure EDC with new bpnl and technical User
- [ ] Deploy everything with new configuration on INT

## Hints for Resolution
- Carefully update and test with EDC and with not EDC on Int 
- Both Users must function correctly

## Additional Information
- The frontend repo is the Main Source of helm charts but the logic of validation roles will be on backend 
- Main configurations can be also changed on vault

**Comment by fabiodmota** [comment]
Quality Gate Done
